/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fields/': RouteRecordInfo<
      '/fields/',
      '/fields',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fields/[id]': RouteRecordInfo<
      '/fields/[id]',
      '/fields/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/jobs/': RouteRecordInfo<
      '/jobs/',
      '/jobs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/me/profile': RouteRecordInfo<
      '/me/profile',
      '/me/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/me/security': RouteRecordInfo<
      '/me/security',
      '/me/security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/me/settings': RouteRecordInfo<
      '/me/settings',
      '/me/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/organization/': RouteRecordInfo<
      '/organization/',
      '/organization',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/organization/create/': RouteRecordInfo<
      '/organization/create/',
      '/organization/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/organization/members': RouteRecordInfo<
      '/organization/members',
      '/organization/members',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/fields/index.vue': {
      routes:
        | '/fields/'
      views:
        | never
    }
    'src/pages/fields/[id].vue': {
      routes:
        | '/fields/[id]'
      views:
        | never
    }
    'src/pages/jobs/index.vue': {
      routes:
        | '/jobs/'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/me/profile.vue': {
      routes:
        | '/me/profile'
      views:
        | never
    }
    'src/pages/me/security.vue': {
      routes:
        | '/me/security'
      views:
        | never
    }
    'src/pages/me/settings.vue': {
      routes:
        | '/me/settings'
      views:
        | never
    }
    'src/pages/organization/index.vue': {
      routes:
        | '/organization/'
      views:
        | never
    }
    'src/pages/organization/create/index.vue': {
      routes:
        | '/organization/create/'
      views:
        | never
    }
    'src/pages/organization/members.vue': {
      routes:
        | '/organization/members'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
