// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteFieldsByIdData, DeleteFieldsByIdResponses, DeleteSeasonsByIdData, DeleteSeasonsByIdResponses, GetFieldsByIdAnalyticsData, GetFieldsByIdAnalyticsResponses, GetFieldsByIdData, GetFieldsByIdErrors, GetFieldsByIdResponses, GetFieldsByIdTilesData, GetFieldsByIdTilesResponses, GetFieldsByIdWorkflowsData, GetFieldsByIdWorkflowsErrors, GetFieldsByIdWorkflowsResponses, GetFieldsData, GetFieldsErrors, GetFieldsResponses, GetHealthzData, GetHealthzResponses, GetOrganizationsData, GetOrganizationsResponses, GetS3ByPathData, GetS3ByPathErrors, GetS3ByPathResponses, GetSeasonsByIdData, GetSeasonsByIdResponses, GetSeasonsData, GetSeasonsResponses, GetTilesByIdMetricsData, GetTilesByIdMetricsErrors, GetTilesByIdMetricsResponses, PostFieldsByIdAnalyticsJobsData, PostFieldsByIdAnalyticsJobsErrors, PostFieldsByIdAnalyticsJobsResponses, PostFieldsByIdBuildPmtilesData, PostFieldsByIdBuildPmtilesResponses, PostFieldsData, PostFieldsErrors, PostFieldsResponses, PostOrganizationsByIdInviteData, PostOrganizationsByIdInviteResponses, PostOrganizationsData, PostOrganizationsResponses, PostSeasonsData, PostSeasonsResponses, PutFieldsByIdData, PutFieldsByIdResponses, PutSeasonsByIdData, PutSeasonsByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Liveness/readiness
 */
export const getHealthz = <ThrowOnError extends boolean = false>(options?: Options<GetHealthzData, ThrowOnError>) => (options?.client ?? client).get<GetHealthzResponses, unknown, ThrowOnError>({ url: '/healthz', ...options });

/**
 * List fields by organization
 */
export const getFields = <ThrowOnError extends boolean = false>(options: Options<GetFieldsData, ThrowOnError>) => (options.client ?? client).get<GetFieldsResponses, GetFieldsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/fields',
    ...options
});

/**
 * Create field
 */
export const postFields = <ThrowOnError extends boolean = false>(options: Options<PostFieldsData, ThrowOnError>) => (options.client ?? client).post<PostFieldsResponses, PostFieldsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/fields',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete field
 */
export const deleteFieldsById = <ThrowOnError extends boolean = false>(options: Options<DeleteFieldsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteFieldsByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/fields/{id}',
    ...options
});

/**
 * Get field
 */
export const getFieldsById = <ThrowOnError extends boolean = false>(options: Options<GetFieldsByIdData, ThrowOnError>) => (options.client ?? client).get<GetFieldsByIdResponses, GetFieldsByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/fields/{id}',
    ...options
});

/**
 * Update field
 */
export const putFieldsById = <ThrowOnError extends boolean = false>(options: Options<PutFieldsByIdData, ThrowOnError>) => (options.client ?? client).put<PutFieldsByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/fields/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Field tiles as GeoJSON FeatureCollection
 */
export const getFieldsByIdTiles = <ThrowOnError extends boolean = false>(options: Options<GetFieldsByIdTilesData, ThrowOnError>) => (options.client ?? client).get<GetFieldsByIdTilesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/fields/{id}/tiles',
    ...options
});

/**
 * Field-level analytics timeseries and PMTiles artifacts
 */
export const getFieldsByIdAnalytics = <ThrowOnError extends boolean = false>(options: Options<GetFieldsByIdAnalyticsData, ThrowOnError>) => (options.client ?? client).get<GetFieldsByIdAnalyticsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/fields/{id}/analytics',
    ...options
});

/**
 * Field processing workflow runs (Temporal status + stage)
 *
 * Lists `FieldProcessingWorkflow` executions for `workflow_id = field-{field_id}`.
 * Running workflows expose a coarse `stage` from pending activities (tiles → GEE → ML → PMTiles → DB).
 * Requires `TEMPORAL_ADDRESS` on the API server. Authenticated users must belong to the field's organization.
 *
 */
export const getFieldsByIdWorkflows = <ThrowOnError extends boolean = false>(options: Options<GetFieldsByIdWorkflowsData, ThrowOnError>) => (options.client ?? client).get<GetFieldsByIdWorkflowsResponses, GetFieldsByIdWorkflowsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/fields/{id}/workflows',
    ...options
});

/**
 * Publish ML jobs to RabbitMQ (legacy path)
 */
export const postFieldsByIdAnalyticsJobs = <ThrowOnError extends boolean = false>(options: Options<PostFieldsByIdAnalyticsJobsData, ThrowOnError>) => (options.client ?? client).post<PostFieldsByIdAnalyticsJobsResponses, PostFieldsByIdAnalyticsJobsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/fields/{id}/analytics-jobs',
    ...options
});

/**
 * Trigger PMTiles build jobs (RabbitMQ)
 */
export const postFieldsByIdBuildPmtiles = <ThrowOnError extends boolean = false>(options: Options<PostFieldsByIdBuildPmtilesData, ThrowOnError>) => (options.client ?? client).post<PostFieldsByIdBuildPmtilesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/fields/{id}/build-pmtiles',
    ...options
});

/**
 * List seasons for field
 */
export const getSeasons = <ThrowOnError extends boolean = false>(options: Options<GetSeasonsData, ThrowOnError>) => (options.client ?? client).get<GetSeasonsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/seasons',
    ...options
});

/**
 * Create season
 */
export const postSeasons = <ThrowOnError extends boolean = false>(options?: Options<PostSeasonsData, ThrowOnError>) => (options?.client ?? client).post<PostSeasonsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/seasons',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const deleteSeasonsById = <ThrowOnError extends boolean = false>(options: Options<DeleteSeasonsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteSeasonsByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/seasons/{id}',
    ...options
});

export const getSeasonsById = <ThrowOnError extends boolean = false>(options: Options<GetSeasonsByIdData, ThrowOnError>) => (options.client ?? client).get<GetSeasonsByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/seasons/{id}',
    ...options
});

export const putSeasonsById = <ThrowOnError extends boolean = false>(options: Options<PutSeasonsByIdData, ThrowOnError>) => (options.client ?? client).put<PutSeasonsByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/seasons/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Organizations for current user
 */
export const getOrganizations = <ThrowOnError extends boolean = false>(options?: Options<GetOrganizationsData, ThrowOnError>) => (options?.client ?? client).get<GetOrganizationsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/organizations',
    ...options
});

/**
 * Create organization
 */
export const postOrganizations = <ThrowOnError extends boolean = false>(options?: Options<PostOrganizationsData, ThrowOnError>) => (options?.client ?? client).post<PostOrganizationsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/organizations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const postOrganizationsByIdInvite = <ThrowOnError extends boolean = false>(options: Options<PostOrganizationsByIdInviteData, ThrowOnError>) => (options.client ?? client).post<PostOrganizationsByIdInviteResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/organizations/{id}/invite',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Observed timeseries + tile predictions (tooltip)
 */
export const getTilesByIdMetrics = <ThrowOnError extends boolean = false>(options: Options<GetTilesByIdMetricsData, ThrowOnError>) => (options.client ?? client).get<GetTilesByIdMetricsResponses, GetTilesByIdMetricsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tiles/{id}/metrics',
    ...options
});

/**
 * Proxy S3/MinIO object (PMTiles; supports Range)
 *
 * Path is everything after /s3/
 */
export const getS3ByPath = <ThrowOnError extends boolean = false>(options: Options<GetS3ByPathData, ThrowOnError>) => (options.client ?? client).get<GetS3ByPathResponses, GetS3ByPathErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/s3/{path}',
    ...options
});
