// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type ErrorBody = {
    error?: string;
};

export type IdResponse = {
    id: string;
};

export type FieldListItem = {
    id?: string;
    name?: string;
    description?: string;
    created_at?: string;
    area_hectares?: number | null;
    organization_id?: string;
    /**
     * Polygon rings [lon, lat], number[][][]
     */
    coordinates?: Array<Array<Array<number>>>;
};

export type FieldDetail = {
    id?: string;
    name?: string;
    description?: string;
    /**
     * Polygon rings [lon, lat]
     */
    coordinates?: Array<Array<Array<number>>>;
    organization_id?: string;
    tile_count?: number;
    season_count?: number;
};

export type CreateFieldRequest = {
    name: string;
    description?: string;
    organization_id: string;
    /**
     * Single polygon exterior + holes
     */
    coordinates: Array<Array<Array<number>>>;
};

export type GeoJsonFeatureCollection = {
    type: unknown;
    features: Array<{
        type?: unknown;
        properties?: {
            tile_id?: string;
        };
        geometry?: {
            [key: string]: unknown;
        };
    }>;
};

export type FieldWorkflowsResponse = {
    field_id: string;
    /**
     * Canonical id when starting workflow
     */
    workflow_id: string;
    workflow_type: string;
    runs: Array<FieldWorkflowRun>;
    listing_note: string;
};

export type FieldWorkflowRun = {
    workflow_id?: string;
    run_id?: string;
    /**
     * RUNNING, COMPLETED, FAILED, etc.
     */
    status?: string;
    /**
     * completed | failed | cut_tiles | geo_metrics | ml_analytics | parallel | finalize_db | …
     *
     */
    stage?: string;
    /**
     * Human-readable stage
     */
    stage_label?: string;
    /**
     * When parallel activities run (e.g. ML + observed PMTiles)
     */
    active_stages?: Array<string>;
    started_at?: string | null;
    closed_at?: string | null;
};

export type FieldAnalyticsResponse = {
    field_id?: string;
    analytics?: Array<FieldAnalyticsRow>;
    pmtiles?: Array<PmtilesArtifact>;
};

export type FieldAnalyticsRow = {
    id?: string;
    field_id?: string;
    observation_date?: string;
    /**
     * observed, derived, or predicted
     */
    source?: string;
    tile_count?: number | null;
    valid_tile_count?: number | null;
    ndvi_mean?: number | null;
    ndmi_mean?: number | null;
    ndre_mean?: number | null;
    gndvi_mean?: number | null;
    msavi_mean?: number | null;
    nbr2_mean?: number | null;
    bare_soil_index_mean?: number | null;
    valid_pixel_ratio_mean?: number | null;
    stress_index_mean?: number | null;
    temperature_c_mean?: number | null;
    precipitation_mm_3d_mean?: number | null;
    precipitation_mm_7d_mean?: number | null;
    precipitation_mm_30d_mean?: number | null;
    /**
     * Degradation heterogeneity (predicted rows)
     */
    heterogeneity_score?: number | null;
    prediction_degradation_score?: number | null;
    prediction_vegetation_cover_loss_score?: number | null;
    prediction_bare_soil_expansion_score?: number | null;
    prediction_health_score?: number | null;
    prediction_stress_score_total?: number | null;
    prediction_water_stress?: number | null;
    prediction_confidence?: number | null;
    prediction_under_irrigation_risk_score?: number | null;
    prediction_over_irrigation_risk_score?: number | null;
    prediction_uniformity_score?: number | null;
    created_at?: string;
};

export type PmtilesArtifact = {
    id?: string;
    field_id?: string;
    analysis_kind?: 'observed' | 'prediction';
    analysis_date?: string;
    /**
     * empty for observed; else degradation, health_stress, irrigation_water_use, predicted
     */
    module?: string;
    pmtiles_url?: string;
    created_at?: string;
};

export type Season = {
    id?: string;
    field_id?: string;
    name?: string;
    start_date?: string;
    end_date?: string;
    is_auto?: boolean;
};

export type TileMetricsResponse = {
    tile_id?: string;
    observed?: Array<{
        observation_date?: string;
        ndvi?: number | null;
        ndmi?: number | null;
        ndre?: number | null;
        valid_pixel_ratio?: number | null;
        stress_index?: number | null;
        temperature_c_mean?: number | null;
        precipitation_mm_3d?: number | null;
        precipitation_mm_7d?: number | null;
        precipitation_mm_30d?: number | null;
    }>;
    predictions?: Array<{
        id?: string;
        module?: 'degradation' | 'health_stress' | 'irrigation_water_use';
        prediction_date?: string;
        status?: string;
        degradation?: {
            [key: string]: unknown;
        };
        health_stress?: {
            [key: string]: unknown;
        };
        irrigation?: {
            [key: string]: unknown;
        };
    }>;
};

export type FieldId = string;

export type GetHealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type GetHealthzResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetHealthzResponse = GetHealthzResponses[keyof GetHealthzResponses];

export type GetFieldsData = {
    body?: never;
    path?: never;
    query: {
        organization_id: string;
    };
    url: '/fields';
};

export type GetFieldsErrors = {
    /**
     * Bad request
     */
    400: ErrorBody;
    /**
     * Not authenticated
     */
    401: ErrorBody;
    /**
     * Server error
     */
    500: ErrorBody;
};

export type GetFieldsError = GetFieldsErrors[keyof GetFieldsErrors];

export type GetFieldsResponses = {
    200: {
        fields: Array<FieldListItem>;
    };
};

export type GetFieldsResponse = GetFieldsResponses[keyof GetFieldsResponses];

export type PostFieldsData = {
    body: CreateFieldRequest;
    path?: never;
    query?: never;
    url: '/fields';
};

export type PostFieldsErrors = {
    /**
     * Bad request
     */
    400: ErrorBody;
    /**
     * Server error
     */
    500: ErrorBody;
};

export type PostFieldsError = PostFieldsErrors[keyof PostFieldsErrors];

export type PostFieldsResponses = {
    201: IdResponse;
};

export type PostFieldsResponse = PostFieldsResponses[keyof PostFieldsResponses];

export type DeleteFieldsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/fields/{id}';
};

export type DeleteFieldsByIdResponses = {
    /**
     * No content
     */
    204: void;
};

export type DeleteFieldsByIdResponse = DeleteFieldsByIdResponses[keyof DeleteFieldsByIdResponses];

export type GetFieldsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/fields/{id}';
};

export type GetFieldsByIdErrors = {
    /**
     * Not found
     */
    404: ErrorBody;
};

export type GetFieldsByIdError = GetFieldsByIdErrors[keyof GetFieldsByIdErrors];

export type GetFieldsByIdResponses = {
    200: FieldDetail;
};

export type GetFieldsByIdResponse = GetFieldsByIdResponses[keyof GetFieldsByIdResponses];

export type PutFieldsByIdData = {
    body?: {
        name: string;
        description?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/fields/{id}';
};

export type PutFieldsByIdResponses = {
    200: IdResponse;
};

export type PutFieldsByIdResponse = PutFieldsByIdResponses[keyof PutFieldsByIdResponses];

export type GetFieldsByIdTilesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/fields/{id}/tiles';
};

export type GetFieldsByIdTilesResponses = {
    200: GeoJsonFeatureCollection;
};

export type GetFieldsByIdTilesResponse = GetFieldsByIdTilesResponses[keyof GetFieldsByIdTilesResponses];

export type GetFieldsByIdAnalyticsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        date_from?: string;
        date_to?: string;
    };
    url: '/fields/{id}/analytics';
};

export type GetFieldsByIdAnalyticsResponses = {
    200: FieldAnalyticsResponse;
};

export type GetFieldsByIdAnalyticsResponse = GetFieldsByIdAnalyticsResponses[keyof GetFieldsByIdAnalyticsResponses];

export type GetFieldsByIdWorkflowsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/fields/{id}/workflows';
};

export type GetFieldsByIdWorkflowsErrors = {
    /**
     * User not in field organization
     */
    403: unknown;
    /**
     * Temporal query error
     */
    502: unknown;
    /**
     * Temporal not configured on API
     */
    503: unknown;
};

export type GetFieldsByIdWorkflowsResponses = {
    200: FieldWorkflowsResponse;
};

export type GetFieldsByIdWorkflowsResponse = GetFieldsByIdWorkflowsResponses[keyof GetFieldsByIdWorkflowsResponses];

export type PostFieldsByIdWorkflowsData = {
    body?: {
        from_date?: string;
        to_date?: string;
        year?: number;
        observation_dates?: Array<string>;
        ml_modules?: Array<'m0' | 'm1' | 'm2'>;
    };
    path: {
        id: string;
    };
    query?: {
        year?: number;
    };
    url: '/fields/{id}/workflows';
};

export type PostFieldsByIdWorkflowsErrors = {
    /**
     * User not in field organization
     */
    403: unknown;
    /**
     * Temporal start error
     */
    502: unknown;
    /**
     * Temporal not configured on API
     */
    503: unknown;
};

export type PostFieldsByIdWorkflowsResponses = {
    202: {
        status?: string;
        field_id?: string;
        workflow_id?: string;
        run_id?: string;
        workflow_type?: string;
    };
};

export type PostFieldsByIdWorkflowsResponse = PostFieldsByIdWorkflowsResponses[keyof PostFieldsByIdWorkflowsResponses];

export type GetFieldsByIdProcessingDatesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/fields/{id}/processing-dates';
};

export type GetFieldsByIdProcessingDatesResponses = {
    200: {
        field_id?: string;
        season_id?: string;
        season_name?: string;
        season_start?: string;
        season_end?: string;
        processing_dates?: Array<{
            date?: string;
            processed?: boolean;
        }>;
    };
};

export type GetFieldsByIdProcessingDatesResponse = GetFieldsByIdProcessingDatesResponses[keyof GetFieldsByIdProcessingDatesResponses];

export type PostFieldsByIdResultsDeleteData = {
    body: {
        dates: Array<string>;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/fields/{id}/results/delete';
};

export type PostFieldsByIdResultsDeleteResponses = {
    200: {
        status?: string;
        dates?: Array<string>;
    };
};

export type PostFieldsByIdResultsDeleteResponse = PostFieldsByIdResultsDeleteResponses[keyof PostFieldsByIdResultsDeleteResponses];

export type PostFieldsByIdAnalyticsJobsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/fields/{id}/analytics-jobs';
};

export type PostFieldsByIdAnalyticsJobsErrors = {
    /**
     * ML publisher not configured
     */
    503: unknown;
};

export type PostFieldsByIdAnalyticsJobsResponses = {
    202: {
        status?: string;
        tiles_total?: number;
        tiles_with_ts?: number;
        jobs_sent?: number;
    };
};

export type PostFieldsByIdAnalyticsJobsResponse = PostFieldsByIdAnalyticsJobsResponses[keyof PostFieldsByIdAnalyticsJobsResponses];

export type PostFieldsByIdBuildPmtilesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/fields/{id}/build-pmtiles';
};

export type PostFieldsByIdBuildPmtilesResponses = {
    202: {
        status?: string;
        jobs_sent?: number;
    };
};

export type PostFieldsByIdBuildPmtilesResponse = PostFieldsByIdBuildPmtilesResponses[keyof PostFieldsByIdBuildPmtilesResponses];

export type GetSeasonsData = {
    body?: never;
    path?: never;
    query: {
        field_id: string;
    };
    url: '/seasons';
};

export type GetSeasonsResponses = {
    200: {
        seasons?: Array<Season>;
    };
};

export type GetSeasonsResponse = GetSeasonsResponses[keyof GetSeasonsResponses];

export type PostSeasonsData = {
    body?: {
        field_id: string;
        name: string;
        start_date: string;
        end_date: string;
        is_auto?: boolean;
    };
    path?: never;
    query?: never;
    url: '/seasons';
};

export type PostSeasonsResponses = {
    201: IdResponse;
};

export type PostSeasonsResponse = PostSeasonsResponses[keyof PostSeasonsResponses];

export type DeleteSeasonsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/seasons/{id}';
};

export type DeleteSeasonsByIdResponses = {
    /**
     * No content
     */
    204: void;
};

export type DeleteSeasonsByIdResponse = DeleteSeasonsByIdResponses[keyof DeleteSeasonsByIdResponses];

export type GetSeasonsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/seasons/{id}';
};

export type GetSeasonsByIdResponses = {
    200: Season;
};

export type GetSeasonsByIdResponse = GetSeasonsByIdResponses[keyof GetSeasonsByIdResponses];

export type PutSeasonsByIdData = {
    body?: {
        name: string;
        start_date: string;
        end_date: string;
        is_auto?: boolean;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/seasons/{id}';
};

export type PutSeasonsByIdResponses = {
    200: IdResponse;
};

export type PutSeasonsByIdResponse = PutSeasonsByIdResponses[keyof PutSeasonsByIdResponses];

export type GetOrganizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/organizations';
};

export type GetOrganizationsResponses = {
    200: {
        organizations?: Array<{
            id?: string;
            name?: string;
        }>;
    };
};

export type GetOrganizationsResponse = GetOrganizationsResponses[keyof GetOrganizationsResponses];

export type PostOrganizationsData = {
    body?: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/organizations';
};

export type PostOrganizationsResponses = {
    201: IdResponse;
};

export type PostOrganizationsResponse = PostOrganizationsResponses[keyof PostOrganizationsResponses];

export type PostOrganizationsByIdInviteData = {
    body?: {
        email: string;
        role?: 'admin' | 'manager' | 'farmer' | 'viewer';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/organizations/{id}/invite';
};

export type PostOrganizationsByIdInviteResponses = {
    201: {
        organization_id?: string;
        user_id?: string;
        role?: string;
    };
};

export type PostOrganizationsByIdInviteResponse = PostOrganizationsByIdInviteResponses[keyof PostOrganizationsByIdInviteResponses];

export type GetTilesByIdMetricsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/tiles/{id}/metrics';
};

export type GetTilesByIdMetricsErrors = {
    /**
     * Not found
     */
    404: ErrorBody;
    /**
     * Not configured
     */
    501: unknown;
};

export type GetTilesByIdMetricsError = GetTilesByIdMetricsErrors[keyof GetTilesByIdMetricsErrors];

export type GetTilesByIdMetricsResponses = {
    200: TileMetricsResponse;
};

export type GetTilesByIdMetricsResponse = GetTilesByIdMetricsResponses[keyof GetTilesByIdMetricsResponses];

export type GetS3ByPathData = {
    body?: never;
    path: {
        path: string;
    };
    query?: never;
    url: '/s3/{path}';
};

export type GetS3ByPathErrors = {
    /**
     * S3 error
     */
    502: unknown;
};

export type GetS3ByPathResponses = {
    /**
     * Full object
     */
    200: unknown;
    /**
     * Partial content
     */
    206: unknown;
};
